/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "1.25rem",
      screens: { "2xl": "1280px" },
    },
    extend: {
      fontFamily: {
        sans: [
          '"Plus Jakarta Sans"',
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
        ],
        numeric: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ['"Instrument Serif"', "Georgia", "serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#4F46E5",
          foreground: "#FFFFFF",
          50: "#F1F0FE",
          100: "#E4E2FD",
          200: "#C9C5FB",
          500: "#4F46E5",
          600: "#4338CA",
          700: "#3730A3",
        },
        mint: {
          DEFAULT: "#10B981",
          dark: "#059669",
          soft: "#E7F8F0",
        },
        ink: {
          DEFAULT: "#0F172A",
          soft: "#334155",
          muted: "#6B7280",
          faint: "#9AA2B1",
        },
        surface: {
          DEFAULT: "#F4F5F7",
          card: "#FFFFFF",
          sunken: "#F8F9FB",
        },
        line: "#EDEFF3",
        /* Landing (light premium) palette */
        void: "#F8FAFF",
        panel: { DEFAULT: "#FFFFFF", hi: "#F3F6FF" },
        chalk: "#0F172A",
        dove: "#475569",
        ghost: "#64748B",
        iris: "#5B6CF8",
        orchid: "#8B5CF6",
        aqua: "#0EA5E9",
        danger: "#EF4444",
        warn: "#F59E0B",
        muted: { DEFAULT: "#F4F5F7", foreground: "#6B7280" },
        accent: { DEFAULT: "#F1F0FE", foreground: "#4F46E5" },
        destructive: { DEFAULT: "#EF4444", foreground: "#FFFFFF" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#0F172A" },
        card: { DEFAULT: "#FFFFFF", foreground: "#0F172A" },
      },
      borderRadius: { xl: "14px", "2xl": "18px", "3xl": "24px" },
      boxShadow: {
        card: "0 1px 2px rgba(16,24,40,0.04), 0 1px 3px rgba(16,24,40,0.03)",
        lift: "0 8px 24px -12px rgba(16,24,40,0.16)",
        pop: "0 16px 40px -18px rgba(37,32,110,0.35)",
        "glow-sm": "0 0 28px -8px rgba(99, 102, 241, 0.55)",
        "glow-md": "0 0 60px -14px rgba(99, 102, 241, 0.5)",
        "glow-lg": "0 24px 120px -24px rgba(139, 92, 246, 0.45)",
      },
      keyframes: {
        "fade-up": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "none" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        float: {
          "0%,100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        shimmer: {
          from: { backgroundPosition: "200% 0" },
          to: { backgroundPosition: "-200% 0" },
        },
        "flow-x": {
          from: { left: "-4%", opacity: "0" },
          "8%, 92%": { opacity: "1" },
          to: { left: "104%", opacity: "0" },
        },
        "scan-y": {
          "0%,100%": { top: "8%", opacity: "0" },
          "12%, 88%": { opacity: "1" },
          "50%": { top: "86%" },
        },
        "divider-flow": {
          from: { backgroundPosition: "0% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        "rotate-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "pulse-soft": {
          "0%,100%": { opacity: "0.45" },
          "50%": { opacity: "1" },
        },
        blink: { "0%,100%": { opacity: "1" }, "50%": { opacity: "0" } },
      },
      animation: {
        "fade-up": "fade-up .32s cubic-bezier(.16,1,.3,1) both",
        float: "float 7s ease-in-out infinite",
        "float-slow": "float 11s ease-in-out infinite",
        shimmer: "shimmer 2.8s linear infinite",
        "flow-x": "flow-x 7s linear infinite",
        "scan-y": "scan-y 5.5s ease-in-out infinite",
        "divider-flow": "divider-flow 6s linear infinite",
        "rotate-slow": "rotate-slow 18s linear infinite",
        "pulse-soft": "pulse-soft 3.4s ease-in-out infinite",
        blink: "blink 1.1s step-end infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
